/**
 * 测试专用 Token 配置
 * 
 * Token 来源：后端文档 /smart_engine/docs/rbac/账号.md
 * 
 * ⚠️ 注意：Token 有有效期，如果失效请从以下途径获取新 Token：
 * 1. 从后端文档 /smart_engine/docs/rbac/账号.md 获取
 * 2. 从浏览器 localStorage 中复制：localStorage.getItem('Admin-Token')
 * 3. 联系后端团队获取新的永久 Token
 */

export const TEST_TOKENS = {
  /** 
   * 超管账号 Token（拥有所有权限）
   * ⚠️ 如果失效，请从 localStorage 复制或联系后端团队
   */
  ADMIN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOiJzeXNfdXNlcjp0aF8wIiwicm5TdHIiOiIzYzVkNTJkNGQ1Y2QzMTc5NTNmNWY5ZDRiNDg1YWJmNCIsImNsaWVudGlkIjoiMDJiYjljZmU4ZDc4NDRlY2FlOGRiZTYyYjFiYTk3MWEiLCJ0ZW5hbnRJZCI6IjAiLCJ1c2VySWQiOiJ0aF8wIiwidXNlck5hbWUiOiJzdXBlcmFkbWluIiwiZGVwdElkIjowLCJkZXB0TmFtZSI6IkRlcHQtMCIsImRlcHRDYXRlZ29yeSI6IiIsInJvbGVzIjpbIlJPTEVfQUxMIl0sInBlcm1pc3Npb25zIjpbInRlbmFudDpkZWxldGU6cmVtb3ZlIiwicGFya19tYW5hZ2VtZW50Iiwicm9sZV9tYW5hZ2VtZW50IiwibG9jYWxfdmlkZW8iLCJjYW1lcmE6bGlzdDp2aWV3IiwibG9nOmxpc3Q6dmlldyIsInZpc3VhbF9jZW50ZXIiLCJyb2xlOnBlcm1pc3Npb246dmlldyIsIndhcm5pbmdfbWFuYWdlbWVudCIsImRldmljZV9za2lsbHMiLCJ2aXN1YWwiLCJyZWFsX3RpbWVfbW9uaXRvcmluZyIsImNvbnRyb2wiLCJyZXZpZXdfcmVjb3JkcyIsImFpLm1vZGVscyIsImRldmljZXMiLCJlZGdlIiwid2FybmluZ19hcmNoaXZlcyIsInN0YXRpc3RpY3NfYW5hbHlzaXMiLCJtb2RlbHMiLCJ1c2VyOnBhc3N3b3JkOnJlc2V0IiwiYXBwbGljYXRpb25fc2V0dGluZ3MiLCJ1c2VyOnJvbGU6dmlldyIsInBlcm1pc3Npb246dXBkYXRlOmVkaXQiLCJsb2dfcmVjb3JkcyIsInNraWxsOmxpc3Q6dmlldyIsInVzZXI6dXBkYXRlOmVkaXQiLCJjYW1lcmFfbWFuYWdlbWVudCIsInVzZXI6Y3JlYXRlOmFkZCIsInRlbmFudDpjcmVhdGU6YWRkIiwicm9sZTpsaXN0OnZpZXciLCJtdWx0aW1vZGFsX3JldmlldyIsInBvc2l0aW9uOmxpc3Q6dmlldyIsInVzZXJfbWFuYWdlbWVudCIsInBvc2l0aW9uX21hbmFnZW1lbnQiLCJjYW1lcmFfbWFuYWdlbWVudF9tYWluIiwibW9uaXRvcmluZyIsImRlcGFydG1lbnRfbWFuYWdlbWVudCIsInNraWxscy5sbG0iLCJwcm9maWxlIiwidGVuYW50OnVwZGF0ZTplZGl0IiwiZWRnZV9ib3g6bGlzdDp2aWV3Iiwic3lzdGVtIiwicGVybWlzc2lvbl9tYW5hZ2VtZW50IiwiY2FtZXJhOmRlbGV0ZTpyZW1vdmUiLCJ1c2VyOmxpc3Q6dmlldyIsImFsZ29yaXRobV9pbmZlcmVuY2UiLCJwb3NpdGlvbjp1cGRhdGU6ZWRpdCIsIm1vZGVsX2xpc3QiLCJ1c2VyOnJvbGU6YXNzaWduOmFkZCIsImVkZ2Vfc2VydmVyOmxpc3Q6dmlldyIsInRlbmFudDpsaXN0OnZpZXciLCJtdWx0aW1vZGFsX2xsbV9za2lsbHMiLCJpbnRlbGxpZ2VudF9yZXZpZXciLCJwb3NpdGlvbjpkZWxldGU6cmVtb3ZlIiwidGVuYW50X21hbmFnZW1lbnQiLCJwYXJrOmxpc3Q6dmlldyIsInJvbGU6ZGVsZXRlOnJlbW92ZSIsImVkZ2VfYm94IiwicGVybWlzc2lvbjpjb2RlOnZhbGlkYXRlIiwiZWRnZV9zZXJ2ZXIiLCJkZXB0OnVwZGF0ZTplZGl0Iiwia25vd2xlZGdlX2Jhc2UiLCJza2lsbHMiLCJwZXJtaXNzaW9uOmNoZWNrOnZlcmlmeSIsInBlcm1pc3Npb246ZGV0YWlsOnZpZXciLCJyb2xlOnBlcm1pc3Npb246cmVtb3ZlOmRlbGV0ZSIsInBlcm1pc3Npb246cm9sZTp2aWV3IiwicGVybWlzc2lvbjpkZWxldGU6cmVtb3ZlIiwidXNlcjpkZWxldGU6YmF0Y2giLCJwZXJtaXNzaW9uOmNyZWF0ZTphZGQiLCJ1c2VyOmRlbGV0ZTpyZW1vdmUiLCJkZXB0OmRlbGV0ZTpyZW1vdmUiLCJwZXJtaXNzaW9uOnRyZWU6dmlldyIsImRlcHQ6Y3JlYXRlOmFkZCIsInJvbGU6Y3JlYXRlOmFkZCIsInVzZXI6cGVybWlzc2lvbjp2aWV3IiwidGVuYW50OmRlbGV0ZTpiYXRjaCIsInBvc2l0aW9uOmNyZWF0ZTphZGQiLCJkZXB0OnRyZWU6dmlldyIsInJvbGU6dXNlcjp2aWV3Iiwicm9sZTp1cGRhdGU6ZWRpdCIsInJvbGUtcGVybWlzc2lvbjphc3NpZ246YWRkIiwicGVybWlzc2lvbjpzdGF0dXM6dXBkYXRlIiwidXNlci1yb2xlOmFzc2lnbjphZGQiLCJkZXB0Omxpc3Q6dmlldyIsInVzZXItcm9sZTpyZW1vdmU6ZGVsZXRlIl0sImV4cCI6MTc3Mzc0OTgzNH0.TPsywlO7heqb9dsdvBG7r_5jKpTkGvPJiqwSYtsgVCA',
  
  /** 普通用户 Token */
  USER: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOiJzeXNfdXNlcjoxOTgyNzE0MTA5NjgwNDk2NjQxIiwicm5TdHIiOiJ0TVo1YjBUZnFvdlVBVkNvcHVqUWdOM0xpRTBRcnQ3MSIsImNsaWVudGlkIjoiMDJiYjljZmU4ZDc4NDRlY2FlOGRiZTYyYjFiYTk3MWEiLCJ0ZW5hbnRJZCI6IjAwMDAwMCIsInVzZXJJZCI6MTk4MjcxNDEwOTY4MDQ5NjY0MSwidXNlck5hbWUiOiJ6dHNNYW5hZ2VyIiwiZGVwdElkIjoxOTgyNzEzNjYzNDE5MTMzOTUzLCJkZXB0TmFtZSI6IiIsImRlcHRDYXRlZ29yeSI6IiJ9.3sVts7xt7-kbKZQ-1z37qqjuwGlAlBm8ugnUvs6CHfE',
} as const;

/**
 * 获取当前浏览器中存储的 Token
 * 在浏览器控制台中运行：getStoredToken()
 */
export function getStoredToken(): string | null {
  if (typeof localStorage !== 'undefined') {
    return localStorage.getItem('Admin-Token');
  }
  return null;
}

/**
 * 设置测试 Token 到 localStorage
 * @param tokenType - Token 类型：'ADMIN' | 'USER'
 */
export function setTestToken(tokenType: 'ADMIN' | 'USER' = 'ADMIN'): void {
  localStorage.setItem('Admin-Token', TEST_TOKENS[tokenType]);
  console.log(`已设置 ${tokenType} Token 到 localStorage`);
}

/**
 * 清除测试 Token
 */
export function clearTestToken(): void {
  localStorage.removeItem('Admin-Token');
  console.log('已清除 Admin-Token');
}
